### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by pexeixv** [xCONFLiCTiONx/XtendedMenu#1]
The repo provides no information regarding how the app is to be downloaded, installed, and used. Please update.

**Comment by xCONFLiCTiONx** [comment]
Thank you for asking! This is intentional as I have made this software the upgraded version of [xMenuTools](https://github.com/xCONFLiCTiONx/xMenuTools#xmenutools). I am not releasing it as a download. I will compile it for any person that donates $10 into my PayPal account.

Below is in the [README.md](https://github.com/xCONFLiCTiONx/XtendedMenu#xtendedmenu)

## How do I download XtendedMenu

You can compile it yourself for free or you can donate $10.00 USD to my PayPal account and I'll compile it myself. Contact me if you would like to donate.
___________________________

I updated it just now:

## How do I download XtendedMenu

You can compile it yourself for free or you can donate $10.00 USD to my [PayPal](https://www.paypal.com/donate?business=FBGPD9E4Z4B9W&amount=10&no_recurring=1&item_name=XtendedMenu&currency_code=USD) account and I'll compile it myself. Contact me if you would like to donate.
